// Fallback copy of the Terms of Service v1.0 (NWM-115), served only when the backend does not answer.
// Same text as the version published in the database (V8.1__seed_legal_documents_v1.sql).
// Not updated at every publication: it only has to keep the page online during an outage.
const body = String.raw`## 1. Term

This agreement commences when the User signs up for the Service and continues until the User terminates their account, or until the account is otherwise terminated in accordance with clause 11, collectively the term of the agreement (“Term”).

## 2. Use of the Service

2.1 Subject to the User signing up for the Service and the restrictions set out in this clause, Newmann hereby grants the User a non-exclusive, non-transferable, non-sublicensable right to use the Service and the Documentation during the Term.

### 2.2 Restricted Material

The User shall not access, store, distribute or transmit any material during the course of its use of the Service that:

- is unlawful, harmful, threatening, defamatory, obscene, infringing, harassing, or racially or ethnically offensive;
- facilitates illegal activity;
- depicts sexually explicit images;
- promotes unlawful violence;
- is discriminatory based on race, gender, colour, religious belief, sexual orientation, or disability; or
- is otherwise illegal or causes damage or injury to any person or property.

Newmann reserves the right, without liability or prejudice to its other rights, to disable the User's access to any material that breaches this clause.

### 2.3 Prohibited Use

The User shall not:

- attempt to copy, modify, duplicate, create derivative works from, frame, mirror, republish, download, display, transmit, or distribute all or any portion of the Software or Documentation in any form or by any means;
- attempt to de-compile, reverse engineer, or otherwise reduce to human-perceivable form all or any part of the Software;
- access the Service in order to build a product or service which competes with the Service;
- use the Service to provide services to third parties on a white-label or resale basis without prior written consent;
- license, sell, rent, lease, transfer, assign, or otherwise commercially exploit the Service to any third party;
- introduce or permit the introduction of any virus or malicious code into Newmann's systems.

2.4 The User shall use all reasonable efforts to prevent any unauthorised access to or use of the Service and shall promptly notify Newmann at [info@newmann.ai](mailto:info@newmann.ai) of any such unauthorised access or use.

## 3. The Service

### 3.1 Capabilities

Newmann provides a cloud-based Software-as-a-Service platform that enables Users to:

- automatically categorise and label incoming emails using customisable, instruction-based labels;
- generate AI-assisted draft replies to incoming emails;
- search and retrieve information from past communications.

### 3.2 Availability

Newmann shall use commercially reasonable efforts to make the Service available 24 hours a day, 7 days a week, except for:

- planned maintenance, of which Newmann will provide reasonable advance notice where possible; and
- unscheduled maintenance or downtime caused by circumstances beyond Newmann's reasonable control.

3.3 Newmann will provide the User with standard support during normal business hours (9:00 am – 6:00 pm CET, Monday to Friday, excluding Italian public holidays), via email at [info@newmann.ai](mailto:info@newmann.ai). Newmann may update its support policy at its discretion from time to time.

3.4 **AI Outputs.** All draft replies and label suggestions generated by the Service are suggestions only. The Service does not send any email automatically. All outgoing communications require the User's explicit review and approval. The User remains solely responsible for the content of any email sent.

## 4. Data Protection

4.1 Both parties shall comply with applicable data protection laws, including the General Data Protection Regulation (EU) 2016/679 (“GDPR”), in connection with this agreement.

4.2 The User consents to Newmann collecting and processing usage data relating to how the User interacts with the Service, for the purpose of operating, maintaining, and improving the platform, as further described in the Privacy Policy available at newmann.ai.

4.3 To the extent Newmann processes personal data contained in the User's emails on the User's behalf, Newmann acts as a Data Processor and the User acts as the Data Controller. The terms governing such processing are set out in the **Data Processing Agreement** contained in Schedule 1 of this document.

### 4.4 Use of AI Providers

Newmann utilises OpenAI (GPT-4o mini) for AI inference and processing. When you use the platform to categorise emails or generate drafts, relevant snippets of email content are sent to OpenAI. The following conditions apply:

- **Data Retention:** In accordance with OpenAI's API policies, data sent via the API is retained by OpenAI for up to 30 days solely for the purpose of identifying abuse and misuse. After this period, the data is deleted from their systems.
- **Model Training:** OpenAI does not use data submitted through its API to train or improve its AI models.
- **Google API Data (Limited Use):** Newmann's use and transfer of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements. Newmann does not use Gmail data to train generalised AI models.

4.5 User data is not used by Newmann to train any public AI model. Aggregated and anonymised usage patterns may be used internally to improve platform performance.

## 5. User Responsibilities

5.1 The User:

- shall provide Newmann with all necessary cooperation and access to information required to provide the Service;
- is solely responsible for ensuring it has a lawful basis for connecting its email systems to the Service and for processing any personal data of third parties (including email correspondents) through the platform;
- shall comply with all applicable laws and regulations in connection with its use of the Service;
- is solely responsible for ensuring that any email content submitted to the Service is accurate, complete, and lawfully held;
- shall not use the Service for any unlawful or fraudulent purpose; and
- is solely responsible for any actions taken on the basis of AI-generated outputs produced by the Service.

5.2 The User acknowledges that AI outputs are probabilistic in nature and may occasionally be inaccurate, incomplete, or inappropriate. The User is responsible for reviewing all generated content before use.

## 6. Intellectual Property

6.1 Newmann and its licensors retain all intellectual property rights in the Service, the Software, and the Documentation. This agreement does not grant the User any rights in respect of Newmann's intellectual property, except as expressly stated herein.

6.2 The User retains all rights in and to its own data (“User Data”) and is solely responsible for its legality, accuracy, and integrity.

6.3 Any feedback, suggestions, or ideas provided by the User to Newmann in connection with the Service may be used by Newmann freely to improve the Service, without any obligation or compensation to the User.

## 7. Charges and Payment

7.0 The Service is currently provided in a “Test Phase” and is offered to the User free of charge. All the provisions set forth in this Section 7 (Charges and Payment) shall only become effective and applicable upon the official conclusion of the Test Phase. Newmann will provide Users with prior notice before the Test Phase ends and before any fees become due.

7.1 The User shall pay the subscription fees applicable to their selected plan as set out on the Subscription Page within the platform.

7.2 At the point of subscribing, the User shall provide valid and complete payment and billing details. The User authorises Newmann to charge the applicable fees in accordance with the selected plan.

7.3 Newmann reserves the right to modify subscription fees at any time upon written notice to the User. Continued use of the Service after the notice period constitutes acceptance of the updated fees.

7.4 Fees are non-refundable except where required by applicable law or as expressly stated in the Subscription Page.

## 8. Confidentiality

8.1 Each party may have access to confidential information of the other party in connection with this agreement. Each party agrees to keep the other party's confidential information secret and not to disclose it to any third party, except as required by law or as necessary to perform its obligations under this agreement.

8.2 These obligations shall survive termination of this agreement for a period of five (5) years.

## 9. Limitation of Liability

9.1 To the maximum extent permitted by applicable law:

- Newmann shall not be liable for any loss of profits, loss of data, loss of business, or any indirect, incidental, special, or consequential loss arising out of or in connection with this agreement, even if advised of the possibility of such damages;
- Newmann's total aggregate liability under or in connection with this agreement shall be limited to the greater of €500 or the total subscription fees paid by the User in the three (3) months preceding the event giving rise to the claim.

9.2 Nothing in this agreement excludes or limits Newmann's liability for death or personal injury caused by its negligence, or for fraud or fraudulent misrepresentation.

9.3 The User remains solely responsible for any decisions made or actions taken based on AI-generated outputs produced by the Service. Newmann does not warrant that outputs will be accurate, complete, or fit for any particular purpose.

## 10. Indemnity

The User shall indemnify and hold harmless Newmann against any claims, losses, damages, costs, and expenses (including reasonable legal fees) arising out of or in connection with: (a) the User's use of the Service in breach of this agreement; (b) any claim that the User's email content or data infringes the rights of any third party; or (c) the User's failure to comply with applicable data protection or other laws.

## 11. Termination

### 11.1 Grounds for Termination

This agreement may be terminated:

- by Newmann, upon 30 days' written notice to the User;
- by either party with immediate effect if the other party commits a material breach of this agreement and, where the breach is capable of remedy, fails to remedy it within 30 days of written notice;
- by the User at any time by cancelling their account through the platform (once this functionality is made available within the platform interface);
- with immediate effect if the User breaches clause 2 of this agreement.

### 11.2 Effects of Termination

Upon termination:

- all licences granted under this agreement shall immediately terminate;
- the User shall cease all use of the Service;
- Newmann may delete User Data in its possession. The User may request a data export within 10 days of the termination date by contacting [info@newmann.ai](mailto:info@newmann.ai); any outstanding payment obligations shall survive termination (subject to the provisions of Section 7.0 regarding the Free Test Phase).

## 12. Modifications to the Service and Terms

12.1 Newmann reserves the right to modify, suspend, or discontinue any aspect of the Service at any time, with reasonable notice where practicable.

12.2 Newmann may update these Terms from time to time. Updated Terms will be posted on the platform with a revised date. Continued use of the Service after the update constitutes acceptance of the revised Terms.

## 13. Force Majeure

Neither party shall be liable for any failure or delay in performance resulting from causes beyond its reasonable control, including acts of God, internet outages, cyberattacks, or regulatory changes. If such circumstances persist for more than 60 days, either party may terminate this agreement upon 15 days' written notice.

## 14. General

14.1 **Entire Agreement.** This agreement, together with the Privacy Policy and the Data Processing Agreement in Schedule 1, constitutes the entire agreement between the parties with respect to its subject matter and supersedes all prior agreements and understandings.

14.2 **Severance.** If any provision of this agreement is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.

14.3 **No Partnership.** Nothing in this agreement creates a partnership, joint venture, or agency relationship between the parties.

14.4 **Assignment.** The User may not assign or transfer any rights or obligations under this agreement without Newmann's prior written consent. Newmann may assign this agreement freely.

14.5 **Waiver.** No failure to enforce any provision of this agreement shall constitute a waiver of that provision.

## 15. Governing Law and Jurisdiction

This agreement and any dispute arising from it shall be governed by and construed in accordance with the laws of Italy. The parties submit to the exclusive jurisdiction of the courts of Milan, Italy.

## 16. Contact

For any queries regarding these Terms, data protection requests, or any other matter related to the Service, please contact:

Newmann

Email: [info@newmann.ai](mailto:info@newmann.ai)

Website: [https://newmann.ai](https://newmann.ai)

---

## Schedule 1 — Data Processing Agreement

Between Newmann (Data Processor) and User (Data Controller)

## DPA 1. Roles of the Parties

1.1 The parties acknowledge and agree that, to the extent Newmann processes Personal Data on the User's behalf in the course of providing the Service:

- the User is the **Data Controller**;
- Newmann is the **Data Processor**;
- the subject matter, duration, nature, purpose, and categories of data processed are set out in Appendix A of this Schedule.

1.2 Any terms not defined in this Data Processing Agreement shall have the meaning set out in the main body of these Terms of Service.

## DPA 2. Compliance

Each party shall comply with all applicable Data Protection Laws in relation to its processing of Personal Data under or in connection with this agreement, including the GDPR and any applicable Italian implementing legislation.

## DPA 3. User Warranties

The User warrants, represents, and undertakes that:

- all Personal Data processed by Newmann on the User's behalf has been collected and is processed in accordance with Data Protection Laws;
- the User has all necessary consents, legal bases, and authorisations in place to enable the lawful transfer of Personal Data to Newmann for the duration and purposes of the agreement; and
- all instructions given by the User to Newmann in respect of the processing of Personal Data shall comply with Data Protection Laws.

## DPA 4. Newmann's Obligations as Processor

Where Newmann processes Personal Data as Data Processor on the User's behalf, Newmann shall:

- only process Personal Data in accordance with the User's lawful, documented, and reasonable instructions, unless required to do so by applicable law;
- inform the User if, in Newmann's opinion, an instruction infringes Data Protection Laws;
- implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including protection against accidental or unlawful destruction, loss, alteration, or unauthorised disclosure of, or access to, Personal Data;
- provide reasonable assistance and cooperation to the User in responding to data subject requests and in meeting the User's obligations under Data Protection Laws, including in respect of security, breach notification, Data Protection Impact Assessments, and prior consultation with supervisory authorities;
- notify the User without undue delay upon becoming aware of a Personal Data breach;
- ensure that all Newmann personnel authorised to process Personal Data are subject to appropriate confidentiality obligations;
- maintain written records of all categories of processing activities carried out on the User's behalf, as required by applicable law; and
- upon written request, delete or return Personal Data to the User within a reasonable period after the end of the provision of the Service, unless retention is required by applicable law.

## DPA 5. Sub-processors

5.1 The User hereby grants Newmann general authorisation to engage sub-processors to assist in the provision of the Service. Newmann shall ensure that all sub-processors are bound by data protection obligations substantially similar to those set out in this Schedule.

### 5.2 Current Sub-processors

| Provider | Role | Data Processed |
|---|---|---|
| Google / Microsoft | Authentication (OAuth) | Account identity data |
| OpenAI | AI inference (GPT-4o mini) | Email content snippets |
| Google Cloud | Backend infrastructure | All platform data |
| Microsoft Azure | Backend hosting | Application and log data |
| Vercel | Frontend hosting | Web traffic data |
| PostHog | Product analytics | Usage and behavioural data |
| Pinecone | Vector database | Semantic embeddings of email content |

5.3 Before engaging any new sub-processor, Newmann shall inform the User. The User may object to the new sub-processor within 10 business days of notification by contacting [info@newmann.ai](mailto:info@newmann.ai), acting reasonably.

5.4 As between Newmann and the User, Newmann shall remain fully liable for the acts and omissions of its sub-processors.

## DPA 6. International Data Transfers

The User authorises Newmann to transfer Personal Data outside the European Economic Area (“EEA”) where required to perform the Service, including to countries where Newmann's sub-processors operate, provided that Newmann ensures that all such transfers are effected in accordance with Data Protection Laws, including through the use of Standard Contractual Clauses (“SCCs”) or other legally recognised transfer mechanisms.

The following providers may process data outside the EEA: OpenAI (United States), Vercel (United States), Pinecone (United States). All such transfers are covered by SCCs.

## DPA 7. Audit Rights

7.1 Newmann shall make available to the User such information as is reasonably necessary to demonstrate compliance with this Data Processing Agreement, and shall allow for and contribute to audits or inspections conducted by the User or an authorised third-party auditor, subject to:

- reasonable prior written notice being provided to Newmann;
- the User bearing Newmann's reasonable costs of assisting with such audit;
- all information obtained being kept strictly confidential; and
- audits being limited to a maximum of one per twelve-month period and conducted with minimal disruption to Newmann's operations.

## DPA 8. Data Subject Rights

Newmann shall assist the User, insofar as reasonably possible and within the scope of Newmann's role as Processor, in fulfilling the User's obligation to respond to requests from data subjects exercising their rights under Data Protection Laws (including rights of access, rectification, erasure, restriction, portability, and objection). All such requests or queries should be directed to [info@newmann.ai](mailto:info@newmann.ai).

## DPA 9. Data Breach Notification

In the event of a Personal Data breach affecting data processed on the User's behalf, Newmann shall notify the User without undue delay and shall provide all reasonably available information to allow the User to meet any notification obligations under applicable Data Protection Laws.

## Appendix A — Data Processing Details

**Subject matter of processing:** Provision of the Newmann email automation Service to the User.

**Nature and purpose of processing:** Processing of email data and related communications to enable AI-assisted categorisation, labelling, and draft reply generation.

**Duration of processing:** For the duration of the Service relationship and thereafter as required by applicable law.

**Categories of data subjects:** The User's employees, collaborators, clients, suppliers, and other third parties whose personal data may appear in email communications processed through the platform.

**Types of personal data processed:** Name, email address, email content (body and subject), sender and recipient information, timestamps, email metadata, attachments (where applicable), account authentication data, and any other personal data incidentally contained in email communications processed through the Service.

### Technical and organisational security measures

- Encryption in transit (HTTPS/TLS) and at rest
- Role-based access control and least-privilege principles
- Structured logging and monitoring
- Regular security assessments
- Multi-factor authentication for Newmann personnel
- Infrastructure hosted on Google Cloud (ISO 27001 / SOC 2 coverage)
`;

export default body;
